version: "3.4"
services:
  db:
    image: postgres
    restart: always
    command: postgres -c listen_addresses='*'
    env_file:
      - .env
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    depends_on:
      - db
    ports:
      - 3000:3000
    env_file:
      - .env
